base_url = "jakecurran.com"

title = "Jake Curran"
description = ""
default_language = "en"

highlight_code = true
highlight_theme = "monokai"

generate_rss = true
compile_sass = true
build_search_index = false

[extra]
